export enum Path {
  HOME = '/',
  ACCORDION = '/accordion',
  AVATAR = '/avatar',
  BUTTON = '/button',
  CARD = '/card',
  CHECKBOX = '/checkbox',
  HAMBURGER = '/hamburger',
  INPUT_TEXT = '/input-text',
  INPUT_TEXT_AREA = '/input-text-area',
  INPUT_RANGE = '/input-range',
  LABEL = '/label',
  LOADING = '/loading',
  MODAL = '/modal',
  SELECT = '/select',
  TOAST = '/toast',
  TOGGLE = '/toggle',
  TOOLTIP = '/tooltip',
  TOOLTIPS = '/tooltips',
  TOOLTIPSB2 = '/tooltips-b2',
  TOOLTIPSB4 = '/tooltips-b4',
  TYPOGRAPHY = '/typography'
}